### PR TITLE
Fix ENS resolution if mainnet not supported

### PR DESCRIPTION
**Pull request by philogicae**
# Found issue:
- [Check issue 350](https://github.com/family/connectkit/issues/350) reported by @SonOfMosiah

# Proposed solution:
- Add useEnsFallbackConfig hook to easily guarantee mainnet access to all ENS-related hooks, regardless of the chains supported by the dapp.

### CODE REVIEW

**Comment by philogicae** [comment]
@lochie 👀

**Review by lochie — APPROVED** [review]
This is a great contribution @philogicae! Sorry for the delay in reviewing this, and many thanks for taking the time to put this together 🙏

**Comment by philogicae** [comment]
Btw @lochie, if you need some help from external reviewers, don't hesitate to reach me. Always happy to contribute to quality open source projects when I have time ✌️

**Comment by lochie** [comment]
> Btw @lochie, if you need some help from external reviewers, don't hesitate to reach me. Always happy to contribute to quality open source projects when I have time ✌️

Thanks @philogicae, I really appreciate that! Will tag you if anything comes up 😊

**Comment by lochie** [comment]
This feature is now available in ConnectKit `1.7.3` 🫡

**Pull request merged**
