### PR TITLE
Enable Trust Wallet connector option

### PR DESCRIPTION
**Pull request by chrisll-nodereal**
Enable Trust Wallet icon and text as an injected connector

### CODE REVIEW

**Comment by chrisll-nodereal** [comment]
This update shows Trust Wallet option on wallet selection list. It also ensures Trust Wallet doesn't disappear when MetaMask and Coinbase Wallet are enabled.

**Comment by chrisll-nodereal** [comment]
@lochie Hi mate, could you please review the code when you get time.

**Review by lochie — APPROVED** [review]
Hey @chrisll-nodereal, I've made a few adjustments and tested on both Trust iOS and the Chrome extension. Seems to work nicely now.

Happy to merge, but I'm not sure why the [additional check](https://github.com/family/connectkit/blob/678eef5632cb1b5f494b6717ecb3914c9eca1934/packages/connectkit/src/components/Pages/Connectors/index.tsx#L91-L93) is necessary, does Trust do something different if MetaMask and Coinbase Wallet are present? 🤔

**Comment by Halibao-Lala** [comment]
Hi @lochie, thanks for the review. It seems Injected wallet option doesn't show when Metamask is connected. The [additional checking](https://github.com/family/connectkit/blob/678eef5632cb1b5f494b6717ecb3914c9eca1934/packages/connectkit/src/components/Pages/Connectors/index.tsx#L91-L93) is to make sure that Trust Wallet option presents when Metamask or Coinbase Wallet is enabled.

**Pull request merged**
