### PR TITLE
Provide `exports.types` in package.json

### PR DESCRIPTION
**Pull request by alex-grover**
Related to #229, the `package.json` is not configured correctly. You can see the warning at https://publint.dev/connectkit@1.5.1 - when `exports` is specified, the top level `types` is ignored.

The workaround in that issue does work, but ConnectKit + TypeScript is broken with the default `create-next-app` template, so I think it's worth fixing. 

By my understanding, there are a couple possible resolutions here:
- Update the `exports` field in the package.json to identify both the js and types file (the approach in this PR)
- Rename the generated files so that the `.d.ts` file matches the name of the js file (i.e. `index.es.d.ts`)

I'm not an expert in getting this stuff set up, but I did test by building locally and linking into an existing project. I believe this issue also exists in `connectkit-next-siwe`, and I'm happy to make the same fix there if desired!

### CODE REVIEW

**Comment by lochie** [comment]
Interesting, I really appreciate the PR! I'm going to look into this a bit more to make sure this config is correct before merging. Thanks 🙏

**Comment by alex-grover** [comment]
of course, let me know if I can help!

**Comment by stinkypablo** [comment]
Seeing `Could not find a declaration file for module 'connectkit'`using next@13.4.19 and connectkit@1.5.2. Believe it's related to this package.json config. Is there any update on this badboy?

**Review by lochie — APPROVED** [review]
This seems to do the trick! Approving but just doing a bit more testing in the background to triple check things. Thanks again 🫡

**Comment by lochie** [comment]
This PR is now available in ConnectKit `1.5.3` 🙌

Thanks @alex-grover 🙏

**Pull request merged**
