### PR TITLE
Remove initialData in nonce and session

### PR DESCRIPTION
**Pull request by JamieLottering**
It appears that in @tanstack/react-query v5 and up the query will not be fetched on mount if `initialData` is anything other than `undefined`. This means that the `ckSiweNonce` and `ckSiweSession` queries don't fire for the first time until their respective intervals have elapsed.

This commit removes the `initialData` for both of these queries in order to restore previous functionality.

Versions used to reproduce issue:
`"@tanstack/react-query": "5.18.1"` & `"connectkit": "1.7.1"`

### CODE REVIEW

**Comment by JamieLottering** [comment]
Hi team, I appreciate you are very busy but I am respectfully asking for some eyes on this. Currently in the process of migrating to viem 2.0 (which requires us to update wagmi to 2.0, react-query to v5, and connectkit to 1.7) and this is the last issue keeping us from wrapping up.

**Review by lochie — APPROVED** [review]
Good catch @JamieLottering! Was on my list to debug why SIWE had an issue when first trying to connect and this seems to resolve those problems 🙌

**Comment by JamieLottering** [comment]
> Good catch @JamieLottering! Was on my list to debug why SIWE had an issue when first trying to connect and this seems to resolve those problems 🙌

Awesome, thank you for merging!!

**Comment by lochie** [comment]
This update is now in ConnectKit `1.7.2`, thanks @JamieLottering 🙌

**Pull request merged**
