### PR TITLE
add enforceSupportedChains option

### PR DESCRIPTION
**Pull request by lochie**
Adds `enforceSupportedChains` option, default set to `false` to follow our current UX
When this option is set to `true` connectkit will no longer force the user to choose a different network if the connected network is unsupported

This option partners well with `initialChainId` being set to `0`

### CODE REVIEW

**Comment by Songkeys** [comment]
LGTM. A doc might be required.

**Comment by lochie** [comment]
> How about something like `autoPopupSwitchNetworkModal`?

@Songkeys I had a few thoughts regarding naming this option, the above doesn't seem quite right to me as this option is a blocking action, so `allow` would make more sense.

Keen to hear other naming options if anyone has more ideas.

**Review by benjitaylor — APPROVED** [review]

**Comment by Songkeys** [comment]
`allowUnsupportedChains` is not intuitive to me (that it's an option for the UI change). But i'm generally okay with this.

**Comment by volkyeth** [comment]
I agree that `allowUnsupportedChains`, despite being accurate, is not very intuitive.  Nothing that the docs can't solve, but it's not very discoverable if you find about it while exploring the API in the code.

What about `enforceSupportedChains`? "Enforcement" better depicts the blocking modal behavior

**Comment by lochie** [comment]
@volkyeth `enforceSupportedChains` currently sounds like the best option, just waiting for some internal discussions before updating this PR

**Comment by Songkeys** [comment]
Hi Lochie. Sorry about this off-topic comment - I made some PR and discussions on family connectkit and would like to contribute more. Do you have plans to setup a discord server cuz it'd be more convenient for roadmaps, communications and questions. Also it'd be more transparent and healthy for the community :)

**Comment by lochie** [comment]
@Songkeys if you could [start a discussion](https://github.com/family/connectkit/discussions/new?category=q-a) regarding this I can get this idea across to our team. We're always appreciating the contributions 😊

**Comment by lochie** [comment]
moving forward with `enforceSupportedChains`, thanks for the suggestion @volkyeth!

**Comment by eduardopelitti** [comment]
Hi folks, sorry to leave a comment on a closed PR but I've been following this discussion for a few days now.

I'm somewhat confused with the final naming you chose. The original naming was `allowUnsupportedChains`, and was set to false as default to maintain the current UX, where the flow is blocked if the app doesn't set an `initialChainId` and is connected to an unsupported network. To me this made sense, if you want to allow unsupported chains, you set it to true and the user can be connected to any network and still navigate the page. If you set it to false, the user is prompted to switch to a supported network in a blocking UX flow.

But `enforceSupportedChains`, to me, reads the other way around. If we are enforcing supported chains, then we are establishing the blocking UX where the user needs to switch. If we are not enforcing the supported chains, then the user can connect on an unsupported chain and the dApp can handle the network switch however it deems fit.

So to me, it's the other way around:

enforceSupportedChains should be set to true to maintain the current UX (And this should probably be the default value)

enforceSupportedChains should be set to false to avoid displaying the network switch prompt (This app does not support the current connected network. Switch or disconnect to continue.) while using initialChainId: 0.

Does it make sense? I feel like it's set the other way around

**Pull request merged**
