### PR TITLE
feat: bump wagmi to 0.11.x and typescript to ^4.9.5

### PR DESCRIPTION
**Pull request by Songkeys**
Following the [wagmi changelog](https://github.com/wagmi-dev/wagmi/releases/tag/wagmi%400.11.0), this should have no breaking change. And we should also upgrade the typescript version to ^4.9.4.

### CODE REVIEW

**Comment by 0xMySt1c** [comment]
running into an npm dependency conflict for wagmi/cli. This would help.

**Comment by alagunoff** [comment]
Waiting for this pr)

**Comment by lochie** [comment]
Sorry about the delay on this, we were waiting for this to come with a larger release with [WalletConnect v2](https://github.com/family/connectkit/pull/108), but since it's been [postponed](https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595) we'll fast track this update.

**Review by lochie — APPROVED** [review]
lgtm

**Comment by lochie** [comment]
Thanks for the PR @Songkeys!

**Pull request merged**
