### PR TITLE
feat: wagmi 2.x support

### PR DESCRIPTION
**Pull request by lochie**
This update brings in support for wagmi 2.x

- Updates peer dependency `wagmi` to `2.x`
- Updates peer dependency `viem` to `2.x`
- Introduces peer dependency `@tanstack/react-query`
- Requires `typescript` to be a minimum of `5.0.4`
- Removes need for `mipd` dependency
- Introduces customisation of default wallets displayed in the modal

---

Fixes: https://github.com/family/connectkit/issues/336

### CODE REVIEW

**Comment by fulminmaxi** [comment]
any ETA for this?
 Sorry to bother you but in the middle of a rewrite and would love to use it, but will stick with wagmi@1 if this still has some time before release

**Comment by lochie** [comment]
> any ETA for this? Sorry to bother you but in the middle of a rewrite and would love to use it, but will stick with wagmi@1 if this still has some time before release

we're just finalising things, it's quite a big update so we're wanting to make sure our migration guide and docs are all up to date as well.

**Comment by lochie** [comment]
@woodybriggs hopefully tomorrow 🙌

**Comment by lochie** [comment]
@woodybriggs heads up that this is now released in ConnectKit version `1.7.0` 🙌

**Comment by woodybriggs** [comment]
Top work!

**Pull request merged**
