### PR TITLE
adds: custom wallet list configuration

### PR DESCRIPTION
**Pull request by lochie**
This PR adds customisability to what wallets are displayed, and the ability to bring in custom wallet configs

### CODE REVIEW

**Comment by Seranged** [comment]
Hey guys, is there any update to implement this functionality into Connectkit?

There's currently a issue with clashing between Metamask and Phantom injectedWallet and this would alleviate it. (Metamask onclick handler for connecting doesn't work when Phantom is enabled in the same browser)

I'm considering migrating to RainbowKit because they have a custom wallet list API with a explicit Metamask hook.

Thanks!

**Comment by MarkNerdi** [comment]
> Hey guys, is there any update to implement this functionality into Connectkit?
> 
> There's currently a issue with clashing between Metamask and Phantom injectedWallet and this would alleviate it. (Metamask onclick handler for connecting doesn't work when Phantom is enabled in the same browser)
> 
> I'm considering migrating to RainbowKit because they have a custom wallet list API with a explicit Metamask hook.
> 
> Thanks!

Same here

**Comment by lochie** [comment]
@Seranged @MarkNerdi We are working on a [PR that implements EIP-6963](https://github.com/family/connectkit/pull/312) which has better handling of wallets which should be merged soon which mostly overrules this PR as wallets will now be fully dynamic.
I've left this PR open as we may still introduce some customisation options for niche use cases, but we want to merge EIP-6963 before moving forward with this PR.

**Comment by smblee** [comment]
@lochie any timeline estimate you can give on this feature? 🙏

**Comment by lochie** [comment]
> @lochie any timeline estimate you can give on this feature? 🙏

this feature is no longer blocked and is next on our feature list. i just need to make some time in the next few days to fix the conflicts and re-review

**Comment by lochie** [comment]
This feature is effectively in public beta as of ConnectKit version `1.7.0`.
This PR is no longer necessary as it was easier to set up in a way that wagmi 2.x supports natively.

Some early documentation can be found here: https://docs.family.co/connectkit/wallets

**Pull request closed without merging**
