### PR TITLE
feat: Add TokenPocket Wallet support

### PR DESCRIPTION
**Pull request by chendatony31**

### CODE REVIEW

**Comment by chendatony31** [comment]
Hi @lochie, I've checked the PR list, seems lots of injected wallets have the same problems. Maybe you can have some common changes about the issue? As lots of wallets have submitted info in `wagmi` repo here: https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/utils/getInjectedName.ts#L6, i think you can using it.

**Review by lochie — APPROVED** [review]

**Comment by lochie** [comment]
Hey @chendatony31, thanks for the PR!
re: injected wallets, we're currently optimising that setup, hopefully this will be in the next release to fix some of these issues and will display the wallet name instead of just "Browser Wallet"

**Review by lochie — CHANGES_REQUESTED** [review]
looks like the svg needs to be converted to jsx, and `xmlns:xlink="http://www.w3.org/1999/xlink"` needs to be removed from the svg tag or the build fails

**Comment by chendatony31** [comment]
Ok, let me see.

**Comment by chendatony31** [comment]
Done @lochie

**Review by lochie — APPROVED** [review]
lgtm!

**Comment by lochie** [comment]
@chendatony31 could you pull the latest from the base branch so I can merge?

**Comment by chendatony31** [comment]
Rebased @lochie

**Comment by lochie** [comment]
will be available in the next release. thanks @chendatony31

**Pull request merged**
