### PR TITLE
Fix unknown chain logo

### PR DESCRIPTION
**Pull request by Bridgerz**
I noticed if the Wagmi configuration has chains not included in the default supported chains list, the "Unknown Chain" logo only appears in the chain select dropdown and not in the ConnectKitModal or ConnectKitButton components. Very easy fix. Thanks for creating such a beautiful project!

### CODE REVIEW

**Comment by Bridgerz** [comment]
@lochie Could we merge this in? its super minimal :)

**Review by lochie — APPROVED** [review]
nice solution, thanks for the contribution @Bridgerz!

**Comment by Bridgerz** [comment]
@lochie When can we expect these changes to reflect in the node package?

**Comment by lochie** [comment]
@Bridgerz we're looking towards some time later this week to push up a patch with these recent changes.
We'll announce it on [Twitter](https://twitter.com/family).

**Pull request merged**
