### PR TITLE
Export ConnectKitOptions

### PR DESCRIPTION
**Pull request by ryanberckmans**
Export ConnectKitOptions so clients may define typed options, eg.

```typescript
import { ConnectKitOptions } from "connectkit";

const myOpts: ConnectKitOptions = {
  hideNoWalletCTA: true,
};
```

### CODE REVIEW

**Review by lochie — CHANGES_REQUESTED** [review]
Hey @ryanberckmans, thanks for the PR!

This is great, but is missing the top-level export from `src/types.ts`. We coudl also probably want to move this type to `src/types.ts` while we're at it, but I don't think that's necessary for now.

I'll make some updates to this PR before merging it in.

**Review by lochie — APPROVED** [review]
Have updated the types in the testbench and exported for usage, good to merge now!

**Comment by lochie** [comment]
@ryanberckmans this feature is now available in ConnectKit v1.1.4! Check out the [release notes here](https://github.com/family/connectkit/releases/tag/v1.1.4).
Thanks again for your contribution ✨

**Comment by ryanberckmans** [comment]
Thanks, cheers! Great library, looking forward to the growth to come.

**Pull request merged**
