### PR TITLE
Add bloom wallet

### PR DESCRIPTION
**Pull request by MarkNerdi**
This PR adds Bloom wallet to the list of available wallets

### CODE REVIEW

**Comment by MarkNerdi** [comment]
@lochie Is something additional needed for this to be reviewable?

**Comment by lochie** [comment]
> @lochie Is something additional needed for this to be reviewable?

connectkit recently updated to support [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963), so this wallet should be supported by default if it injects a provider using this new protocol 🙌

closing this PR as it should no longer be necessary to add wallets in manually, but we do appreciate the PR!  ✨

**Comment by MarkNerdi** [comment]
@lochie 
But this is a desktop wallet and doesn't inject anything. So to be able to let the DApp developers to show this wallet on the modal, i think this is still needed?

**Comment by nicole-obrien** [comment]
@lochie Please consider reopening and reviewing this PR, as mentioned Bloom is a desktop wallet and is relies soley on WalletConnect for interacting with dApps in the browser. We do not inject wallets into the dApps web page because we do not have a browser extension. This would be good to add so dApps in the IOTA and Shimmer ecosystem can easily list Bloom to connect to. Many thanks, Nicole [bloomwallet.io](bloomwallet.io)

**Pull request closed without merging**
